# swain shell launcher — zsh
# Auto-generated by swain-init. See: skills/swain-init/templates/launchers/
# Version: 4.0.0
#
# Launches Claude Code interactively with swain's recommended flags.
# Handles tmux wrapping: outside tmux, starts a new tmux session;
# inside tmux, launches claude directly in the current pane.

swain() {
  if [ -z "$TMUX" ]; then
    tmux new-session -s swain "claude --chrome --allow-dangerously-skip-permissions '/swain-init'"
  else
    claude --chrome --allow-dangerously-skip-permissions '/swain-init'
  fi
}
